# Generated by Django 5.0.4 on 2024-05-08 07:19

import django.db.models.deletion
import portals.choices
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
                ('buffer_time', models.IntegerField(default=30)),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('contact_no', models.CharField(max_length=256)),
                ('company_logo', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('zip_code', models.CharField(max_length=256)),
                ('street_address', models.CharField(max_length=256)),
                ('package', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee_type', models.CharField(default='Beginner', max_length=256, verbose_name=portals.choices.PriceChoices)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.service')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('mobile_number', models.CharField(max_length=256)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('bio', models.CharField(max_length=256)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service_provider.service')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('day', models.CharField(max_length=20)),
                ('opening_time', models.TimeField(default='09:00')),
                ('closing_time', models.TimeField(default='17:00')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.service')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('mobile_number', models.CharField(max_length=256)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('bio', models.CharField(max_length=256)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.service')),
            ],
            options={
                'ordering': ('-created_on',),
                'abstract': False,
            },
        ),
    ]
